# Generated by Django 2.0.3 on 2018-11-19 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=255, verbose_name='First Line of Address')),
                ('line2', models.CharField(blank=True, max_length=255, verbose_name='Second Line of Address')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('postal_code', models.CharField(blank=True, max_length=64, verbose_name='Postal Code')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_unit', models.CharField(max_length=20, verbose_name='Area Unit')),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bedrooms')),
                ('home_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Home Size')),
                ('home_type', models.CharField(blank=True, max_length=40, null=True, verbose_name='Home Type')),
                ('price', models.PositiveIntegerField(blank=True, verbose_name='Price')),
                ('price_last_sold', models.PositiveIntegerField(blank=True, null=True, verbose_name='Price Last Sold')),
                ('date_last_sold', models.DateField(blank=True, null=True, verbose_name='Date Last Sold')),
                ('rent', models.PositiveIntegerField(blank=True, verbose_name='Rent')),
                ('property_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Property Size')),
                ('tax_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tax Value')),
                ('tax_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tax Year')),
                ('year_built', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year Built')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Address')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('abbreviation', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Abbreviation')),
            ],
            options={
                'verbose_name_plural': 'States',
                'verbose_name': 'State',
            },
        ),
        migrations.CreateModel(
            name='ZillowInformation',
            fields=[
                ('zillow_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='First Line of Address')),
                ('link', models.CharField(blank=True, max_length=2000, verbose_name='Link')),
                ('rent_est', models.PositiveIntegerField(blank=True, null=True, verbose_name='Zestimate Rent')),
                ('rent_est_last_updated', models.DateField(blank=True, verbose_name='Zestimate Rent Last Updated')),
                ('price_est', models.PositiveIntegerField(blank=True, null=True, verbose_name='Zestimate Price')),
                ('price_est_last_updated', models.DateField(blank=True, verbose_name='Zestimate Price Last Updated')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='zillow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ZillowInformation'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.State'),
        ),
    ]
