# Generated by Django 2.0.3 on 2018-11-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial_set_up_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='tax_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tax Year'),
        ),
        migrations.AlterField(
            model_name='property',
            name='year_built',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Year Built'),
        ),
    ]
